# app/agentic/topics.py

from enum import Enum

class AgenticTopic(Enum):
    USER_INPUT = "USER_INPUT_TOPIC"
    ENGAGEMENT_OUTPUT = "ENGAGEMENT_OUTPUT_TOPIC"
    REFINED_QUERY_TOPIC = "REFINED_QUERY_TOPIC"
    CLUSTER_ROUTED_QUERY_TOPIC = "CLUSTER_ROUTED_QUERY_TOPIC"
    # 🔁 Ambiguous flow
    CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED_TOPIC"
    CLARIFICATION_REPLY = "CLARIFICATION_REPLY_TOPIC"

    # 📚 RAG + Final
    RAG_RETRIEVAL_OUTPUT = "RAG_RETRIEVAL_OUTPUT_TOPIC"
    FINAL_RESPONSE = "FINAL_RESPONSE_TOPIC"
    