# app/agentic/topics.py

from enum import Enum

class AgenticTopic(Enum):
    USER_INPUT = "USER_INPUT_TOPIC"
    ENGAGEMENT_OUTPUT = "ENGAGEMENT_OUTPUT_TOPIC"
    REFINED_QUERY_TOPIC = "REFINED_QUERY_TOPIC"
    CLUSTER_ROUTED_QUERY_TOPIC = "CLUSTER_ROUTED_QUERY_TOPIC"
    RAG_RETRIEVAL_OUTPUT = "RAG_RETRIEVAL_OUTPUT_TOPIC"
    FINAL_RESPONSE = "FINAL_RESPONSE_TOPIC"
    